spring:
  application:
    name: eureka-client-turbine
server:
  port: 8769
turbine:
  aggregator:
    cluster-config: default
  app-config: eureka-feign-client,eureka-ribbon-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
